Update

diff --git a/centos7/systemd/httpd/apache/Dockerfile b/centos7/systemd/httpd/apache/Dockerfile
--- a/centos7/systemd/httpd/apache/Dockerfile
+++ b/centos7/systemd/httpd/apache/Dockerfile
@@ -11,89 +11,44 @@
 #@  DOCKER_PUBLISHED="${DOCKER_IMAGEPATH}"
 #
 
-# SSH Login
-ARG ENABLE_SSHD=""
-
 # Logrotate
-ARG LOGROTATION=""
+ARG LOGROTATION="YES"
+
+# Enable SUDO
+ARG ENABLE_SUDO="YES"
+
+# SSH Login
+ARG ENABLE_SSHD="YES"
 
 # Extra RPM Packages
 ARG ONBUILD_RPM_PACKAGES="httpd mod_ssl"
 
 # OnBuild Script
-ARG ONBUILD_SHELL_SCRIPT=""
+ARG ONBUILD_SHELL_SCRIPT="httpd-apache_onbuild.sh"
 
-# Apache HTTP Server on CentOS7 with Systemd
+# Image fromp
 FROM centos7:systemd-onbuild
-
-# Set Workdir
-WORKDIR /tmp/docker-container-image-build
-
-# Copy contents to Workdir
-COPY * ./
 
 # SetUp
 RUN \
- set -ux; \
- work_dir=$(pwd); \
- : "Tests" && { \
-  [ -x "$(type -P httpd)" ] || { \
-   echo "command 'httpd' not found." 1>&2; \
-   exit 1; }; \
-  echo "Remove 'welcome'." && { \
-   mv -fv /usr/share/httpd/{noindex/images,icons}/poweredby.png; \
-   rm -fv "/etc/httpd/conf.d/welcome.conf"; \
-   rm -rfv "/usr/share/httpd/noindex"/*; \
-  }; \
- } && \
- : "Update httpd.conf" && { \
-  httpdcnf="/etc/httpd/conf/httpd.conf"; \
-  : && { \
-   [ -e "${httpdcnf}.ORIG" ] || \
-   cp -pf "${httpdcnf}"{,.ORIG}; \
-  } && \
-  if [ -e "./httpd.conf" -a -s "./httpd.conf" ]; \
-  then cat "./httpd.conf" 1>"${httpdcnf}"; \
-  else \
-   cat "${httpdcnf}.ORIG" | \
-   sed -r \
-    -e 's/^[#[:space:]]*(ServerAdmin)[[:space:]]+.*$/\1 admin@localhost/gi' \
-    -e 's/^[#[:space:]]*(ServerTokens)[[:space:]]+.*$/\1 Prod/gi' \
-    -e 's/^[#[:space:]]*(ServerSignature)[[:space:]]+.*$/\1 Off/gi' \
-    -e 's/^[#[:space:]]*(AddDefaultCharset)[[:space:]]+.*$/\1 UTF-8/gi' \
-    1>"${httpdcnf}"; \
-  fi && \
-  /usr/sbin/httpd -t; \
- } && \
- : "Enable httpd service." && { \
-  systemctl enable httpd; \
- } && \
- : "YUM Cleanup." && { \
-  yum -v -y clean all || :; \
-  [ -d "/var/cache/yum/" ] && \
-  rm -rf /var/cache/yum/* || :; \
- } && \
- : "Cleanup." && { \
-  cd /; \
-  [ -d "/var/log" ] && for lf in /var/log/*; \
-  do [ -f "${lf}" -a -s "${lf}" ] && : >"${lf}"; \
-  done || :; \
-  rm -rf {,/var}/tmp/* "${work_dir:-X}" || :; \
- } && \
- : "Done.";
+ set -ux; work_dir=$(pwd); \
+ [ -x "$(type -P httpd)" ] || { \
+  echo "command 'httpd' not found"; \
+  exit 1; }; \
+ systemctl enable httpd
 
 # Reset Workdir
 WORKDIR /
 
 # Labels
 LABEL \
- name="Base Image for Apache HTTP Server on CentOS7 with Systemd" \
+ name="Apache HTTP Server on CentOS7 with Systemd" \
  vendor="UGOOLE.ORG" \
  maintainer="MT" \
  license="" \
- docker.build.options="" \
- docker.run.options="-d -P -h centos7s-httpd-apache --privileged --expose=80 --expose=443" \
- docker.run.confirm-startup=""
+ org.ugoole.options.docker.build="" \
+ org.ugoole.options.docker.run="-d -P -h centos7-systemd-httpd-apache --privileged --expose=80 --expose=443" \
+ org.ugoole.docker.run.confirm-startup=""
 
 # STOP SIGNAL
 STOPSIGNAL SIGINT
@@ -110,7 +65,6 @@ HEALTHCHECK \
 CMD \
  curl -sL --no-keepalive -o /dev/null "http://localhost/"
 
-
 # ONBUILD: Set Workdir
 ONBUILD \
 WORKDIR /tmp/docker-container-image-build
@@ -122,27 +76,31 @@ COPY * ./
 # ONBUILD: SetUp
 ONBUILD \
 RUN \
- set -ux; \
- work_dir=$(pwd); \
+ set -ux; work_dir=$(pwd); \
  : "ONBUILD: Setup" && { \
   { [ ! -e "./etc.tgz" ] || tar -zxvf "./etc.tgz"; } && \
   { [ ! -d "./etc" ] || (cd "./etc/" && tar -cv . |tar -C /etc -xf - ); } && \
   { [ ! -e "./www.tgz" ] || tar -zxvf "./www.tgz"; } && \
   { [ ! -d "./www" ] || (cd "./www/" && tar -cv . |tar -C /var/www -xf - ); } && \
-  { [ ! -e "./setup.sh" ] || /bin/bash -ux ./setup.sh; } && \
+  : "Run setup" && { \
+   [ ! -e "./setup.sh" ] || \
+   /bin/bash -ux -o errtrace -o functrace -o pipefail \
+   ./setup.sh; \
+  } && \
   /usr/sbin/httpd -t && \
   echo "OK"; \
  }; \
  : "ONBUILD: YUM Cleanup." && { \
+  yum -v -y remove $(echo $( \
+   package-cleanup --leaves )) || :; \
   yum -v -y clean all || :; \
   [ -d "/var/cache/yum/" ] && \
   rm -rf /var/cache/yum/* || :; \
  } && \
- : "ONBUILD: Cleanup." && { \
-  cd /; \
-  [ -d "/var/log" ] && for lf in /var/log/*; \
+ : "ONBUILD: Cleanup" && { \
+  cd / && [ -d "/var/log" ] && for lf in /var/log/*; \
   do [ -f "${lf}" -a -s "${lf}" ] && : >"${lf}"; \
-  done || :; \
+  done || :; rm -f /var/lib/rpm/__db.* || :; \
   rm -rf {,/var}/tmp/* "${work_dir:-X}" || :; \
  } && \
  : "ONBUILD: Done.";
