Update

diff --git a/centos6-init/pg9x/Dockerfile b/centos6-init/pg9x/Dockerfile
--- a/centos6-init/pg9x/Dockerfile
+++ b/centos6-init/pg9x/Dockerfile
@@ -3,7 +3,7 @@
 #
 #@  DOCKER_CONTAINER=""
 #@  DOCKER_IMAGE_TAG="centos6-init:pg9x"
-#@  DOCKER_BUILDER_OPTS=
+#@  DOCKER_BUILDER_OPTS=""
 #@  DOCKER_STARTUP_OPTS="-h pg9x-server"
 #@  CONTAINER_NOT_START=""
 #@  CONFIRM_STARTUP_CMD=""
@@ -17,7 +17,7 @@ MAINTAINER MT
 # ONBUILD
 # ------------------------------
 
-# Work dir.
+# Work dir
 ONBUILD \
 ARG \
  WORKDIR=/tmp/workdir
@@ -28,12 +28,40 @@ WORKDIR \
 # PostgreSQL Version
 ONBUILD \
 ARG \
- PGSQL_VERSION=""
+ PGSQLVER=""
 
 # pgTap Version
 ONBUILD \
 ARG \
- PGTAP_VERSION=""
+ PGTAPVER=""
+
+# PGDATA
+ONBUILD \
+ARG \
+ PGPDATA=""
+
+# PGPORT
+ONBUILD \
+ARG \
+ PGPORT=""
+
+# Update sysconfig
+ONBUILD \
+RUN \
+ set -x; \
+ pgsysconf="/etc/sysconfig/postgresql"; \
+ [ -n "$PGDATA" ] && { \
+  grep -E '^[ ]*PGDATA='${PGDATA}'[ ]*$' "$pgsysconf" 1>/dev/null 2>&1 || { \
+   echo "Update PGDATA = '$PGDATA'."; \
+   sed -i 's/^[ ]*PGDATA=[^ ]*[ ]*$/PGDATA='${PGDATA}'/g' "$pgsysconf"; \
+ }; }; \
+ [ -n "$PGPORT" ] && { \
+  grep -E '^[ ]*PGPORT='${PGPORT}'[ ]*$' "$pgsysconf" 1>/dev/null 2>&1 || { \
+   echo "Update PGPORT = '$PGPORT'."; \
+   sed -i 's/^[ ]*PGPORT=[^ ]*[ ]*$/PGPORT='${PGPORT}'/g' "$pgsysconf"; \
+ }; }; \
+ echo "$pgsysconf" && \
+ cat "$pgsysconf"
 
 # Install postgresql
 ONBUILD \
@@ -41,13 +69,13 @@ ARG \
  PG_CONFIGURE_OPTIONS=""
 ONBUILD \
 RUN \
- [ -n "$PGSQL_VERSION" ] || { \
-  echo "'PGSQL_VERSION' is not set !!" 1>&2; \
+ [ -n "$PGSQLVER" ] || { \
+  echo "'PGSQLVER' is not set !!" 1>&2; \
   exit 127; \
  }; \
  set -x; . /etc/sysconfig/postgresql && \
- pgname="postgresql-${PGSQL_VERSION}" && \
- pg_ver="${PGSQL_VERSION}" && \
+ pgname="postgresql-${PGSQLVER}" && \
+ pg_ver="${PGSQLVER}" && \
  pg_url="https://ftp.postgresql.org/pub/source/v${pg_ver}/${pgname}.tar.gz" && \
  curl -s -o - "${pg_url}" |tar -zpxvf - && \
  ( cd "${pgname}" && \
@@ -58,19 +86,24 @@ RUN \
     rm -rf "${PGHOME}-latest"; \
     ln -sf "${PGHOME}-${pg_ver}" "${PGHOME}-latest"; \
    } && \
+   for dir in "${PGHOME}/archivelogs" "${PGDATA}"; do \
+    [ -d "$dir" ] || mkdir -p "$dir"; \
+    chown "${PGUSER}:${PGUSER}" "$dir" && \
+    chmod 2750 "$dir"; \
+   done && \
    for dir in bin include lib share; do \
-    rm -rf "./$dir"; ln -sf "${PGHOME}-latest/$dir" .; \
-   done; ) && \
- rm -rf "./${pgname}"*
+    [ -e "$dir" ] && rm -rf "./$dir"; \
+    ln -sf "${PGHOME}-latest/$dir" .; \
+   done; )
 
 # Install pgTAP
 ONBUILD \
 RUN \
- if [ -n "${PGTAP_VERSION}" ]; \
+ if [ -n "${PGTAPVER}" ]; \
  then \
   set -x; . /etc/sysconfig/postgresql && \
-  pgtapname="pgtap-${PGTAP_VERSION}" && \
-  pgtap_ver="${PGTAP_VERSION}" && \
+  pgtapname="pgtap-${PGTAPVER}" && \
+  pgtap_ver="${PGTAPVER}" && \
   pgtap_url="http://api.pgxn.org/dist/pgtap/${pgtap_ver}/${pgtapname}.zip" && \
   curl -s -o - "${pgtap_url}" |unzip - && \
   ( export PATH="$PATH:${PGHOME}/bin" && \
@@ -78,13 +111,13 @@ RUN \
     make && make install; ) && \
   rm -rf "./${pgtapname}"*; \
  else \
-  echo "'PGTAP_VERSION' is not set, skipping."; \
+  echo "'PGTAPVER' is not set, skipping."; \
  fi
 
 # Install pg_prove
 ONBUILD \
 RUN \
- if [ -n "${PGTAP_VERSION}" ]; \
+ if [ -n "${PGTAPVER}" ]; \
  then \
   set -x; \
   export PERL_AUTOINSTALL='--defaultdeps' && \
@@ -92,22 +125,13 @@ RUN \
   cpan -i TAP::Parser::SourceHandler::pgTAP && \
   rm -rf /root/.cpan; \
  else \
-  echo "'PGTAP_VERSION' is not set, skipping."; \
+  echo "'PGTAPVER' is not set, skipping."; \
  fi 
-
-# Init database
-ONBUILD \
-ARG \
- PG_INITDB_OPTIONS="-E UTF-8 --locale=C"
-ONBUILD \
-RUN \
- set -x; . /etc/sysconfig/postgresql && \
- su "${PGUSER}" -c "LANG= ${PGHOME}/bin/initdb ${PG_INITDB_OPTIONS} ${PGDATA}"
 
 # Setup default config
 ONBUILD \
 COPY \
- *.conf ${WORKDIR}/
+ data/*.conf ${WORKDIR}/
 ONBUILD \
 RUN \
  set -x; . /etc/sysconfig/postgresql && \
@@ -120,6 +144,18 @@ RUN \
    chmod 0644 "${PGDATA}/${config}"; } || break; \
  done
 
+# Init database
+ONBUILD \
+ARG \
+ PG_INITDB_OPTIONS="-E UTF-8 --locale=C"
+ONBUILD \
+RUN \
+ set -x; . /etc/sysconfig/postgresql && \
+    [ -d "$dir" ] || mkdir -p "$dir"; \
+    chown "${PGUSER}:${PGUSER}" "$dir" && \
+    chmod 2750 "$dir"; \
+ su "${PGUSER}" -c "LANG= ${PGHOME}/bin/initdb ${PG_INITDB_OPTIONS} ${PGDATA}"
+
 # Add to the service
 ONBUILD \
 RUN \
@@ -128,7 +164,18 @@ RUN \
  /sbin/chkconfig --levels 2345 postgresql on; \
  /sbin/chkconfig --list |grep postgresql
 
-# Cleanup workdir
+# Cleanup
+ONBUILD \
+RUN \
+ set -x; \
+ for log in /var/log/*; do \
+  cat /dev/null >"$log"; \
+ done; \
+ for log in /tmp/*.log; do \
+  rm -f "$log"; \
+ done
+
+# Work dir reset
 ONBUILD \
 WORKDIR \
  /
@@ -137,7 +184,7 @@ RUN \
  rm -rf "${WORKDIR}"
 
 # ------------------------------
-# SETUP ENVIRONMENTS
+# BUILD THIS IMAGE
 # ------------------------------
 
 # Install packages for PostgreSQL (and pgTAP)
@@ -165,16 +212,16 @@ ARG \
 RUN \
  set -x; . /etc/sysconfig/postgresql && \
  groupadd -g "${PG_UID:-26}" "${PGUSER}" && \
- useradd -u "${PG_UID:-26}" -g "${PGUSER}" -m "${PGUSER}" && \
+ useradd -u "${PG_UID:-26}" -g "${PGUSER}" -d "${PGHOME}" -m "${PGUSER}" && \
  echo "${PGUSER}:${PGPASSWORD:-$PGUSER}" |chpasswd
 
-# Setup postgres/.bashrc
+# Setup $PGHOME
 RUN \
  set -x; . /etc/sysconfig/postgresql && \
- [ -d "/home/${PGUSER}" ] || { \
-  mkdir -p "/home/${PGUSER}" && \
-  chown "${PGUSER}:${PGUSER}" "/home/${PGUSER}" && \
-  chmod 0755 "/home/${PGUSER}"; \
+ [ -d "${PGHOME}" ] || { \
+  mkdir -p "${PGHOME}" && \
+  chown "${PGUSER}:${PGUSER}" "${PGHOME}" && \
+  chmod 0755 "${PGHOME}"; \
  }; \
  : && { \
   echo && \
@@ -182,25 +229,14 @@ RUN \
   echo 'if [ -r "/etc/sysconfig/postgresql" ]' && \
   echo 'then' && \
   echo '  . /etc/sysconfig/postgresql' && \
-  echo '  export PGHOME PGDATA PGPORT' && \
+  echo '  export PGUSER PGHOME PGDATA PGPORT' && \
   echo 'fi' && \
   echo '[ -n "${PGHOME}" ] &&' && \
   echo '[ -d "${PGHOME}/bin" ] &&' && \
   echo '[ -z "$(type -p psql)" ] &&' && \
   echo 'export PATH="${PATH}:${PGHOME}/bin"' && \
   echo; \
- } >>"/home/${PGUSER}/.bashrc"
-
-# Setup $PGHOME
-RUN \
- set -x; . /etc/sysconfig/postgresql && \
- mkdir -p ${PGHOME} && cd "${PGHOME}" && \
- chown -R "${PGUSER}:${PGUSER}" . && chmod -R 2755 . && \
- for dir in "${PGHOME}/archivelogs" "${PGDATA}"; do \
-  { mkdir -p "$dir" && \
-    chown "${PGUSER}:${PGUSER}" "$dir" && \
-    chmod 0700 "$dir"; } || break; \
- done
+ } >>"${PGHOME}/.bashrc"
 
 # Install init and db build script
 COPY \
@@ -224,4 +260,5 @@ RUN \
  for log in /tmp/*.log; do \
   rm -f "$log"; \
  done
+
 
