Update

diff --git a/_docker-bin/functions/docker-dockerfile b/_docker-bin/functions/docker-dockerfile
--- a/_docker-bin/functions/docker-dockerfile
+++ b/_docker-bin/functions/docker-dockerfile
@@ -2,61 +2,60 @@
 
 # Docker file get
 dockerfile-get-path() {
-  local _dockerfile="${1:-}"; shift
-  [ -z "${_dockerfile}" ] &&
-   _dockerfile="$(pwd)/Dockerfile" || :
-  [ -d "${_dockerfile}" ] &&
-   _dockerfile="${_dockerfile}/Dockerfile" || :
-  [ "${_dockerfile}" = "${_dockerfile##*/}" ] &&
-   _dockerfile="$(pwd)/${_dockerfile}" || :
-  [ -n "${_dockerfile}" ] && echo "${_dockerfile}"
+  local _buildpath="${1:-}"; shift
+  [ -z "${_buildpath}" ] &&
+   _buildpath="$(pwd)/Dockerfile" || :
+  [ -d "${_buildpath}" ] &&
+   _buildpath="${_buildpath}/Dockerfile" || :
+  [ "${_buildpath}" = "${_buildpath##*/}" ] &&
+   _buildpath="$(pwd)/${_buildpath}" || :
+  [ -n "${_buildpath}" ] && echo "${_buildpath}"
   return $?
 }
 
 # number of stage
 dockerfile-num-of-stage() {
-  local _dockerfile=$(dockerfile-get-path "${1:-}" 2>/dev/null); shift
-  local _stagecount=$(dockerfile-stage-list "${_dockerfile}"|wc -l 2>/dev/null)
-  echo ${_stagecount:-0}
+  local _buildpath=$(dockerfile-get-path "${1:-}" 2>/dev/null); shift
+  local _stage_num=$(dockerfile-stage-list "${_buildpath}"|wc -l 2>/dev/null)
+  echo ${_stage_num:-0}
   return 0
 }
 
 # multi-stage dockerfile
 dockerfile-multi-stage() {
-  local _stagecount=$(dockerfile-num-of-stage "${1:-}" 2>/dev/null)
-  [ ${_stagecount:-0} -gt 1 ]
+  local _stage_num=$(dockerfile-num-of-stage "${1:-}" 2>/dev/null)
+  [ ${_stage_num:-0} -gt 1 ]
   return $?
 }
 
 # list stage
 dockerfile-stage-list() {
-  local _dockerfile=""
-  local _prt_format=0
-  while [ $# -gt 0 ]
+  local _buildpath=""
+  local _formatted=0
+  eval $(getoptions "f|format=_formatted" "$@")
+  while getoptions_has_next
   do
-    case "${1:-}" in
-    -f|--format*)
-      _prt_format=1
-      ;;
+    eval $(getoptions_shift)
+    case "${_getopt_V:=}" in
     -*)
-      echo "${FUNCNAME}: ERROR: Illegal options '${1:-}'". 1>&2
+      echo "${FUNCNAME}: ERROR: Illegal options '${_getopt_V}'". 1>&2
       return 2
       ;;
     *)
-      [ -z "${_dockerfile}" ] && {
-        _dockerfile="${1:-}"
+      [ -z "${_buildpath}" ] && {
+        _buildpath="${_getopt_V}"
       } || :
       ;;
     esac
-    shift
   done
-  _dockerfile="$(dockerfile-get-path ${_dockerfile} 2>/dev/null)"
-  [ -f "${_dockerfile}" -a -r "${_dockerfile}" ] && {
-    [ ${_prt_format} -eq 0 ] || {
+  eval $(getoptions_end)
+  _buildpath="$(dockerfile-get-path ${_buildpath} 2>/dev/null)"
+  [ -f "${_buildpath}" -a -r "${_buildpath}" ] && {
+    [ ${_formatted} -eq 0 ] || {
       printf "%3s %-24s%s" "IDX" "From" "As"; echo
     }
-    egrep -i '^[[:space:]]*FROM[[:space:]]+' "${_dockerfile}" |
-    if [ ${_prt_format} -eq 0 ]
+    egrep -i '^[[:space:]]*FROM[[:space:]]+' "${_buildpath}" |
+    if [ ${_formatted} -eq 0 ]
     then ${AWK} '{print(NR-1,$2,$4);}'
     else ${AWK} '{print(sprintf("%3d %-24s%s",NR-1,$2,$4));}'
     fi 2>/dev/null
@@ -66,106 +65,123 @@ dockerfile-stage-list() {
 
 # Get stage name by index
 dockerfile-stage-get-name() {
-  local _stageindex="${1:-}"; shift
-  local _dockerfile=$(dockerfile-get-path "${1:-}" 2>/dev/null); shift
-  [ -n "${_stageindex}" ] && {
-    _stageindex="${_stageindex##*#}"
-    dockerfile-stage-list "${_dockerfile}" |
-    ${AWK} '$1=="'"${_stageindex}"'" {print($3);}'
+  local _stage_ind="${1:-}"; shift
+  local _buildpath=$(dockerfile-get-path "${1:-}" 2>/dev/null); shift
+  [ -n "${_stage_ind}" ] && {
+    _stage_ind="${_stage_ind##*+}"
+    dockerfile-stage-list "${_buildpath}" |
+    ${AWK} '$1=="'"${_stage_ind}"'" {print($3);}'
   }
   return $?
 }
 
 # Get stage index by name
 dockerfile-stage-get-index() {
-  local _stage_name="${1:-}"; shift
-  local _dockerfile=$(dockerfile-get-path "${1:-}" 2>/dev/null); shift
-  [ -n "${_stage_name}" ] && {
-    _stage_name="${_stage_name##*@}"
-    dockerfile-stage-list "${_dockerfile}" |
-    ${AWK} '$3=="'"${_stage_name}"'" {print($1);}'
+  local _stagename="${1:-}"; shift
+  local _buildpath=$(dockerfile-get-path "${1:-}" 2>/dev/null); shift
+  [ -n "${_stagename}" ] && {
+    _stagename="${_stagename##*@}"
+    dockerfile-stage-list "${_buildpath}" |
+    ${AWK} '$3=="'"${_stagename}"'" {print($1);}'
   }
   return $?
 }
 
 # Exists stage index
 dockerfile-stage-has-index() {
-  local _stageindex="${1:-}"; shift
-  local _dockerfile=$(dockerfile-get-path "${1:-}" 2>/dev/null); shift
-  [ -n "${_stageindex}" ] && {
-    _stageindex="${_stageindex##*#}"
-    _stageindex=$(
-      dockerfile-stage-list "${_dockerfile}" |
-      ${AWK} '$1=="'"${_stageindex}"'" {print($1);}' 2>/dev/null; )
-    [ -n "${_stageindex}" ]
+  local _stage_ind="${1:-}"; shift
+  local _buildpath=$(dockerfile-get-path "${1:-}" 2>/dev/null); shift
+  [ -n "${_stage_ind}" ] && {
+    _stage_ind="${_stage_ind##*+}"
+    _stage_ind=$(
+      dockerfile-stage-list "${_buildpath}" |
+      ${AWK} '$1=="'"${_stage_ind}"'" {print($1);}' 2>/dev/null; )
+    [ -n "${_stage_ind}" ]
   }
   return $?
 }
 
 # Get stage name by index
 dockerfile-imagetag-get() {
-  local _stageindex=""
-  local _stage_name=""
-  local _cimgtagsuf=""
-  local _stage_spec="${1:-}"; shift
-  local _dockerfile=$(dockerfile-get-path "${1:-}" 2>/dev/null); shift
-  dockerfile-multi-stage "${_dockerfile}" 1>/dev/null 2>&1
-  if [ $? -eq 0 ]
+  local _stage_ind=""
+  local _stagename=""
+  local _cimagetag=""
+  local _stage_key="${1:-}"; shift
+  local _buildpath=$(dockerfile-get-path "${1:-}" 2>/dev/null); shift
+  local _multi_stg=0
+  _cimagetag=$(dockerfile-env-get DOCKER_IMAGE_TAG "${_buildpath}" 2>/dev/null) || {
+    return 1
+  }
+  dockerfile-multi-stage "${_buildpath}" 1>/dev/null 2>&1 && {
+    _multi_stg=1
+  } || :
+  [ ${_multi_stg} -eq 0 ] && {
+    [ -n "${_cimagetag}" ] && echo "${_cimagetag}"
+    return $?
+  } || :
+  case "${_stage_key}" in
+  +[0-9]*)
+    _stage_ind="${_stage_key##*+}"
+    dockerfile-stage-has-index "${_stage_ind}" "${_buildpath}" 1>/dev/null 2>&1 && {
+      _stagename=$(
+        dockerfile-stage-get-name "${_stage_ind}" "${_buildpath}" 2>/dev/null)
+    } || return 2
+    ;;
+  @[0-9A-Za-z]*)
+    _stagename="${_stage_key##*@}"
+    _stage_ind=$(
+      dockerfile-stage-get-index "${_stagename}" "${_buildpath}" 2>/dev/null)
+    ;;
+  *)
+    _stage_ind=""
+    _stagename=""
+    ;;
+  esac
+  if [ -z "${_stage_ind}${_stagename}" ]
   then
-    case "${_stage_spec}" in
-    \#[0-9]*|[0-9]*)
-      _stageindex="${_stage_spec##*#}"
-      dockerfile-stage-has-index "${_stageindex}" "${_dockerfile}" 1>/dev/null 2>&1 && {
-        _stage_name=$(
-          dockerfile-stage-get-name "${_stageindex}" "${_dockerfile}" 2>/dev/null)
-      } || return 2
+    _stage_key=$(dockerfile-stage-list "${_buildpath}" |awk '{print($1);}' 2>/dev/null)
+  else
+    _stage_key="${_stage_ind}"
+  fi
+  [ -n "${_stage_key}" ] &&
+  for _stage_ind in ${_stage_key}
+  do
+    _stagename=$(dockerfile-stage-get-name "${_stage_ind}" "${_buildpath}" 2>/dev/null)
+    case "${_cimagetag}" in
+    [0-9A-Za-z]*:*)
+      if [ -n "${_stagename}" ]
+      then echo "${_cimagetag}${_stagename:+@${_stagename}}"
+      else echo "${_cimagetag}${_stage_ind:+#${_stage_ind}}"
+      fi
       ;;
-    @[0-9A-Za-z]*|[A-Za-z]*)
-      _stage_name="${_stage_spec##*@}"
-      _stageindex=$(
-        dockerfile-stage-get-index "${_stage_name}" "${_dockerfile}" 2>/dev/null)
+    [0-9A-Za-z]*)
+      if [ -n "${_stagename}" ]
+      then echo "${_cimagetag}${_stagename:+:${_stagename}}"
+      else echo "${_cimagetag}${_stage_ind:+:#${_stage_ind}}"
+      fi
       ;;
     *)
       ;;
     esac
-  fi
-  _cimage_tag=$(
-    dockerfile-env-get DOCKER_IMAGE_TAG "${_dockerfile}" 2>/dev/null)
-  case "${_cimage_tag}" in
-  [0-9A-Za-z]*:*)
-    if [ -n "${_stage_name}" ]
-    then _cimage_tag="${_cimage_tag}${_stage_name:+@${_stage_name}}"
-    else _cimage_tag="${_cimage_tag}${_stageindex:+#${_stageindex}}"
-    fi
-    ;;
-  [0-9A-Za-z]*)
-    if [ -n "${_stage_name}" ]
-    then _cimage_tag="${_cimage_tag}${_stage_name:+:${_stage_name}}"
-    else _cimage_tag="${_cimage_tag}${_stageindex:+:#${_stageindex}}"
-    fi
-    ;;
-  *)
-    ;;
-  esac
-  [ -n "${_cimage_tag}" ] && echo "${_cimage_tag}"
+  done
   return $?
 }
 
 # dockerfile get env
 dockerfile-env-get() {
-  local _cattribute="${1:-}"; shift
-  local _dockerfile=$(dockerfile-get-path "${1:-}"); shift
-  local _cattrvalue=""
-  [ -f "${_dockerfile}" -a -r "${_dockerfile}" ] && {
-    if [ -z "${_cattribute}" ]
-    then dockerfile-attributes-get "${_dockerfile}"
+  local _cattr_key="${1:-}"; shift
+  local _buildpath=$(dockerfile-get-path "${1:-}"); shift
+  local _cattr_val=""
+  [ -f "${_buildpath}" -a -r "${_buildpath}" ] && {
+    if [ -z "${_cattr_key}" ]
+    then dockerfile-attributes-get "${_buildpath}"
     else
-      _cattrvalue=$(eval $(
-        dockerfile-attributes-get "${_dockerfile}" |
-        egrep '^'"${_cattribute}"'=.*' 2>/dev/null &&
-        echo 'echo $'"${_cattribute}") )
-      [ -n "${_cattrvalue}" ] && {
-        echo "${_cattrvalue}"
+      _cattr_val=$(eval $(
+        dockerfile-attributes-get "${_buildpath}" |
+        egrep '^'"${_cattr_key}"'=.*' 2>/dev/null &&
+        echo 'echo $'"${_cattr_key}") )
+      [ -n "${_cattr_val}" ] && {
+        echo "${_cattr_val}"
       }
     fi #2>/dev/null
   }
@@ -174,33 +190,37 @@ dockerfile-env-get() {
 
 # docker attributes get
 dockerfile-attributes-get() {
-  local _dockerfile=""
-  local _exportvars=""
-  local _d_variable=""
-  while [ $# -gt 0 ]
+  local _buildpath=""
+  local _exportflg=0
+  local _dvariable=""
+  eval $(getoptions "E|export=_exportflg" "$@")
+  while getoptions_has_next
   do
-    case "$1" in
-    -E|--export)
-      _exportvars="export "
-      ;;
+    eval $(getoptions_shift)
+    case "${_getopt_V:=}" in
     -*)
+      echo "${FUNCNAME}: ERROR: Illegal options '${_getopt_V}'". 1>&2
+      return 2
       ;;
     *)
-      [ -z "${_dockerfile}" ] && {
-        _dockerfile="${1:-}"
+      [ -z "${_buildpath}" ] && {
+        _buildpath="${_getopt_V}"
       } || :
       ;;
     esac
-    shift
   done
-  _dockerfile=$(dockerfile-get-path "${_dockerfile}")
-  [ -r "${_dockerfile}" ] && {
-    cat "${_dockerfile}" |
+  eval $(getoptions_end)
+  _buildpath=$(dockerfile-get-path "${_buildpath}")
+  [ -r "${_buildpath}" ] && {
+    cat "${_buildpath}" |
     ${SED} -ne 's;^#@[ ]*\([_A-Za-z][_0-9A-Za-z]*\)[ ]*=[ ]*\(.*\)[ ]*$;\1=\2;gp' |
-    while read _d_variable
+    while read _dvariable
     do
-      [ -n "$_d_variable" ] &&
-      echo $_exportvars"${_d_variable};"
+      [ -z "${_dvariable}" ] || {
+        [ ${_exportflg} -ne 0 ] &&
+        echo "export ${_dvariable};" ||
+        echo "${_dvariable};"
+      }
     done
   } #2>/dev/null
   return $?
diff --git a/_docker-bin/functions/docker-images-load b/_docker-bin/functions/docker-images-load
--- a/_docker-bin/functions/docker-images-load
+++ b/_docker-bin/functions/docker-images-load
@@ -1,12 +1,23 @@
 # docker image loader
 docker-images-load() {
-  local _load_file="$1"; shift
+  local _imagefile=""
   local _cimage_id=""
   local _cimagetag=""
+  local _cimg_pref=""
+  local _cimg_suff=""
   local _gunzipcmd=""
-  [ -r "$_load_file" ] && {
-    _cimagetag="${_load_file##*/}"
-    case "$_cimagetag" in
+  local _dockerret=0
+  for _imagefile in "${@}"
+  do
+    _cimagetag=""
+    _cimg_pref=""
+    _cimg_suff=""
+    [ -r "${_imagefile}" ] || {
+      echo "$FUNCNAME: Unable to read file '${_imagefile}'." 1>&2
+      continue
+    }
+    _cimagetag="${_imagefile##*/}"
+    case "${_cimagetag}" in
     *.tar.gz)
       _cimagetag="${_cimagetag%.tar.gz*}"
       _gunzipcmd="gunzip -c"
@@ -20,14 +31,26 @@ docker-images-load() {
       _gunzipcmd="cat"
       ;;
     esac
+    case "${_cimagetag}" in
+    *=*)
+      _cimg_pref="${_cimagetag%%:*}"
+      _cimagetag="${_cimg_pref//_/\/}:${_cimagetag#*:}"
+      ;;
+    *)
+      _cimagetag="${_cimagetag//_/\/}"
+      ;;
+    esac
     _cimage_id=$(
-      $_gunzipcmd "$_load_file" |
-      docker load -q |
-      sed -e 's/^Loaded image ID: //g') &&
-    echo "$FUNCNAME: Loaded image ID: $_cimage_id." &&
-    docker tag "$_cimage_id" "$_cimagetag" &&
-    echo "$FUNCNAME: Tagged '$_cimagetag' to '$_cimage_id'."
-  }
+      ${_gunzipcmd} "${_imagefile}" |docker load -q |
+      ${SED} -re 's/^Loaded[[:space:]]+image[[:space:]]+ID:[[:space:]]+//gi') &&
+    docker tag "${_cimage_id}" "${_cimagetag}" ||
+    _dockerret=$?
+    if [ ${_dockerret} -eq 0 ]
+    then echo "$FUNCNAME: Loaded image ID: ${_cimage_id} Tag: '${_cimagetag}'."
+    else echo "$FUNCNAME: Failed to load image: ${_imagefile}." 1>&2
+    fi
+  done &&
+  [ ${_dockerret} -eq 0 ]
   return $?
 }
 
diff --git a/_docker-bin/functions/docker-images-save b/_docker-bin/functions/docker-images-save
--- a/_docker-bin/functions/docker-images-save
+++ b/_docker-bin/functions/docker-images-save
@@ -1,32 +1,74 @@
 # docker image saver
 docker-images-save() {
+  local _cimg_keys=""
+  local _cimagekey=""
   local _cimage_id=""
   local _cimagetag=""
+  local _buildpath=""
   local _store_dir=""
-  eval $(getoptions "d|:=_store_dir" "$@")
+  local _stage_key=""
+  local _savedfile=""
+  local _file_pref=""
+  local _dockerret=0
+  eval $(getoptions "d|:=_store_dir f|:=_buildpath" "$@")
   while getoptions_has_next
   do
     eval $(getoptions_shift)
-    case "$_getopt_V" in
+    case "${_getopt_V:=}" in
     -*)
       ;;
     *)
-      _cimage_id=$(get-image-id "$_getopt_V") &&
-      _cimagetag=$(get-image-tag "$_cimage_id") &&
-      break
+      _cimage_id=$(container-image-get-id "${_getopt_V}") && {
+        _cimg_keys="${_cimg_keys:+${_cimg_keys} }${_cimage_id}"
+      }
+      _cimage_id=""
       ;;
     esac
   done
-  [ -r "$(pwd)/Dockerfile" -a -z "${_cimage_id}" ] && {
-    _cimage_id=$(get-image-id)
-    _cimagetag=$(get-image-tag)
-  }
-  [ -n "$_cimage_id" ] &&
-  [ -n "$_cimagetag" ] && {
-    docker save "$_cimage_id" |
-    gzip -c 1>"${_store_dir:-.}/${_cimagetag/\//_}".tar.gz 2>/dev/null &&
-    echo "$FUNCNAME: Saved image: $_cimagetag($_cimage_id)."
-  }
+  eval $(getoptions_end)
+  [ -z "${_cimg_keys}" ] && {
+    _buildpath=$(dockerfile-get-path "${_buildpath}") || :
+    [ -r "${_buildpath}" ] && {
+      for _cimagetag in $(dockerfile-imagetag-get - "${_buildpath}")
+      do
+        [ -n "${_cimagetag}" ] && {
+          _cimg_keys="${_cimg_keys:+${_cimg_keys} }${_cimagetag}"
+        } || break
+      done
+    }
+    _cimage_id=""
+    _cimagetag=""
+  } || :
+  [ -n "${_cimg_keys}" ] &&
+  for _cimagekey in ${_cimg_keys}
+  do
+    _cimage_id=""
+    _cimagetag=""
+    [ -n "${_cimagekey}" ] && {
+      _cimage_id=$(container-image-get-id "${_cimagekey}")
+      _cimagetag=$(container-image-get-tag "${_cimagekey}")
+    } 2>/dev/null
+    [  -n "${_cimage_id}" -a -n "${_cimagetag}" ] && {
+      case "${_cimagetag}" in
+      *:*)
+        _file_pref="${_cimagetag%%:*}"
+        _savedfile="${_file_pref/\//_}=${_cimagetag#*:}.tgz"
+        ;;
+      *)
+        _savedfile="${_cimagetag/\//_}.tgz"
+        ;;
+      esac
+      docker save "${_cimage_id}" |
+      gzip -c 1>"${_store_dir:-.}/${_savedfile}.tgz" 2>/dev/null
+    } ||
+    _dockerret=$?
+    if [ ${_dockerret} -eq 0 ]
+    then echo "$FUNCNAME: Saved image: '${_cimagetag:-${_cimagekey}}${_cimage_id:+(${_cimage_id})}' to '${_savedfile}'."
+    else echo "$FUNCNAME: Failed to save image: '${_cimagetag:-${_cimagekey}}${_cimage_id:+(${_cimage_id})}'."
+    fi
+    _savedfile=""
+  done &&
+  [ ${_dockerret} -eq 0 ]
   return $?
 }
 
